export const CEFR = {0:"A1", 1:"A2", 2:"B1", 3:"B2", 4:"C1", 5:"C2"};

export const ITEM_DIFFICULTY = [-2.0, -1.0, 0.0, 1.0, 2.0, 3.0];

export const QUESTIONS = [
{"id":"a1-1","level":0,"type":"Grammar","cat":"Basic","q":"___ is a cat.","opts":["A","An","The","This"],"a":0,"b":-2.3},
{"id":"a1-2","level":0,"type":"Grammar","cat":"Basic","q":"I have ___ apple.","opts":["a","an","the","one"],"a":1,"b":-2.29},
{"id":"a1-3","level":0,"type":"Grammar","cat":"Basic","q":"___ sun is hot.","opts":["A","An","The","One"],"a":2,"b":-2.28},
{"id":"a1-4","level":0,"type":"Grammar","cat":"Basic","q":"She ___ a student.","opts":["am","is","are","be"],"a":1,"b":-2.27},
{"id":"a1-5","level":0,"type":"Grammar","cat":"Basic","q":"They ___ happy.","opts":["am","is","are","be"],"a":2,"b":-2.26},
{"id":"a1-6","level":0,"type":"Grammar","cat":"Basic","q":"He ___ not at home.","opts":["am","is","are","be"],"a":1,"b":-2.25},
{"id":"a1-7","level":0,"type":"Grammar","cat":"Basic","q":"I ___ a teacher.","opts":["am","is","are","be"],"a":0,"b":-2.24},
{"id":"a1-8","level":0,"type":"Grammar","cat":"Basic","q":"We ___ from Iran.","opts":["am","is","are","be"],"a":2,"b":-2.23},
{"id":"a1-9","level":0,"type":"Grammar","cat":"Basic","q":"This is ___ book.","opts":["I","my","me","mine"],"a":1,"b":-2.22},
{"id":"a1-10","level":0,"type":"Grammar","cat":"Basic","q":"___ is your name?","opts":["What","How","Who","Where"],"a":0,"b":-2.21},
{"id":"a1-11","level":0,"type":"Grammar","cat":"Basic","q":"I ___ like coffee.","opts":["don't","doesn't","not","am not"],"a":0,"b":-2.2},
{"id":"a1-12","level":0,"type":"Grammar","cat":"Basic","q":"She ___ like tea.","opts":["don't","doesn't","not","isn't"],"a":1,"b":-2.19},
{"id":"a1-13","level":0,"type":"Grammar","cat":"Basic","q":"___ you like music?","opts":["Does","Do","Are","Is"],"a":1,"b":-2.18},
{"id":"a1-14","level":0,"type":"Grammar","cat":"Basic","q":"I have two ___ .","opts":["cat","cats","cat's","caties"],"a":1,"b":-2.17},
{"id":"a1-15","level":0,"type":"Grammar","cat":"Basic","q":"The ___ are playing.","opts":["child","childs","children","childes"],"a":2,"b":-2.16},
{"id":"a1-16","level":0,"type":"Vocabulary","cat":"Basic","q":"What color is the sky?","opts":["Red","Blue","Green","Yellow"],"a":1,"b":-2.15},
{"id":"a1-17","level":0,"type":"Vocabulary","cat":"Basic","q":"How many legs does a dog have?","opts":["Two","Three","Four","Five"],"a":2,"b":-2.14},
{"id":"a1-18","level":0,"type":"Vocabulary","cat":"Basic","q":"What day comes after Monday?","opts":["Sunday","Tuesday","Wednesday","Friday"],"a":1,"b":-2.13},
{"id":"a1-19","level":0,"type":"Vocabulary","cat":"Basic","q":"January is a ___.","opts":["day","month","year","week"],"a":1,"b":-2.12},
{"id":"a1-20","level":0,"type":"Vocabulary","cat":"Basic","q":"Water is a ___.","opts":["food","drink","toy","color"],"a":1,"b":-2.11},
{"id":"a1-21","level":0,"type":"Vocabulary","cat":"Basic","q":"I eat ___ for breakfast.","opts":["bread","water","air","stone"],"a":0,"b":-2.1},
{"id":"a1-22","level":0,"type":"Vocabulary","cat":"Basic","q":"My mother is my ___.","opts":["parent","sister","aunt","cousin"],"a":0,"b":-2.09},
{"id":"a1-23","level":0,"type":"Vocabulary","cat":"Basic","q":"I have two ___ and ten fingers.","opts":["hands","heads","noses","mouths"],"a":0,"b":-2.08},
{"id":"a1-24","level":0,"type":"Vocabulary","cat":"Basic","q":"I wear a ___ on my head.","opts":["hat","shoe","glove","sock"],"a":0,"b":-2.07},
{"id":"a1-25","level":0,"type":"Vocabulary","cat":"Basic","q":"A dog is an ___.","opts":["animal","plant","food","color"],"a":0,"b":-2.06},
{"id":"a1-26","level":0,"type":"Vocabulary","cat":"Basic","q":"The ___ is raining.","opts":["weather","sun","moon","star"],"a":0,"b":-2.05},
{"id":"a1-27","level":0,"type":"Vocabulary","cat":"Basic","q":"I sleep in a ___.","opts":["bed","table","chair","door"],"a":0,"b":-2.04},
{"id":"a1-28","level":0,"type":"Vocabulary","cat":"Basic","q":"My ___ is red.","opts":["car","car's","cars","caring"],"a":0,"b":-2.03},
{"id":"a1-29","level":0,"type":"Vocabulary","cat":"Basic","q":"One, two, three, ___.","opts":["five","four","six","seven"],"a":1,"b":-2.02},
{"id":"a1-30","level":0,"type":"Vocabulary","cat":"Basic","q":"The opposite of big is ___.","opts":["small","tall","long","high"],"a":0,"b":-2.01},
{"id":"a1-31","level":0,"type":"Reading","cat":"Basic","q":"Tom is 10. He has a dog named Max. Max is brown and white. What color is Max?","opts":["Brown","White","Brown and white","Black"],"a":2,"b":-2.0},
{"id":"a1-32","level":0,"type":"Reading","cat":"Basic","q":"Anna wakes up at 7 am. She eats breakfast at 7:30. She goes to school at 8. What does Anna do at 7?","opts":["Eats breakfast","Wakes up","Goes to school","Sleeps"],"a":1,"b":-1.99},
{"id":"a1-33","level":0,"type":"Reading","cat":"Basic","q":"The store sells apples for $1 and oranges for $2. How much for one apple?","opts":["$1","$2","$3","$0.50"],"a":0,"b":-1.98},
{"id":"a1-34","level":0,"type":"Reading","cat":"Basic","q":"There are 5 birds in the tree. 2 fly away. How many are left?","opts":["2","3","5","7"],"a":1,"b":-1.97},
{"id":"a1-35","level":0,"type":"Reading","cat":"Basic","q":"My house has 3 rooms. How many rooms?","opts":["1","2","3","4"],"a":2,"b":-1.96},
{"id":"a2-1","level":1,"type":"Grammar","cat":"Present Continuous","q":"She ___ to music now.","opts":["listens","is listening","listened","will listen"],"a":1,"b":-1.1},
{"id":"a2-2","level":1,"type":"Grammar","cat":"Past Simple","q":"We ___ to Paris last summer.","opts":["go","goes","went","gone"],"a":2,"b":-1.1},
{"id":"a2-3","level":1,"type":"Grammar","cat":"Comparatives","q":"My phone is ___ than yours.","opts":["cheap","cheaper","cheapest","more cheaper"],"a":1,"b":-1.0},
{"id":"a2-4","level":1,"type":"Grammar","cat":"Prepositions","q":"Afraid ___ spiders?","opts":["from","with","of","about"],"a":2,"b":-1.2},
{"id":"a2-5","level":1,"type":"Grammar","cat":"Future","q":"They ___ finish next week.","opts":["will","are","have","did"],"a":0,"b":-1.1},
{"id":"a2-6","level":1,"type":"Grammar","cat":"Quantifiers","q":"How ___ sugar do you want?","opts":["many","much","some","any"],"a":1,"b":-1.0},
{"id":"a2-7","level":1,"type":"Grammar","cat":"Present Perfect","q":"I have ___ finished.","opts":["yet","already","still","ever"],"a":1,"b":-0.9},
{"id":"a2-8","level":1,"type":"Grammar","cat":"Present Simple","q":"She ___ to school by bus.","opts":["go","goes","going","went"],"a":1,"b":-1.0},
{"id":"a2-9","level":1,"type":"Grammar","cat":"There is/are","q":"There ___ a book on the table.","opts":["am","is","are","be"],"a":1,"b":-1.2},
{"id":"a2-10","level":1,"type":"Vocabulary","cat":"Travel","q":"A ___ catches planes.","opts":["bus station","train station","airport","harbor"],"a":2,"b":-1.0},
{"id":"a2-11","level":1,"type":"Vocabulary","cat":"Daily","q":"Eat ___ when hungry.","opts":["water","food","sleep","air"],"a":1,"b":-1.0},
{"id":"a2-12","level":1,"type":"Vocabulary","cat":"Clothes","q":"Wear a ___ when cold.","opts":["t-shirt","coat","shorts","swimsuit"],"a":1,"b":-1.0},
{"id":"a2-13","level":1,"type":"Vocabulary","cat":"Nature","q":"The ___ shines bright.","opts":["moon","sun","star","cloud"],"a":1,"b":-1.0},
{"id":"a2-14","level":1,"type":"Vocabulary","cat":"Daily","q":"___ your teeth every day.","opts":["Wash","Clean","Brush","Dry"],"a":2,"b":-0.99},
{"id":"a2-15","level":1,"type":"Vocabulary","cat":"People","q":"A ___ teaches students.","opts":["doctor","teacher","driver","cook"],"a":1,"b":-1.0},
{"id":"a2-16","level":1,"type":"Reading","cat":"Comprehension","q":"She woke late, ran to the bus stop, bus left. What first?","opts":["She waited","Bus left","Woke up","Got dressed"],"a":2,"b":-1.0},
{"id":"a2-17","level":1,"type":"Reading","cat":"Comprehension","q":"Tom loves being in the kitchen. Every Saturday he picks a new recipe and tries to make it. Last week he made lasagna from scratch. What does Tom do?","opts":["Goes out","Tries recipes","Eats pasta","Cooks meat"],"a":1,"b":-0.99},
{"id":"b1-1","level":2,"type":"Grammar","cat":"Present Perfect","q":"I ___ never ___ to Japan.","opts":["have...be","have...been","has...been","did...go"],"a":1,"b":0.11},
{"id":"b1-2","level":2,"type":"Grammar","cat":"Conditionals","q":"If it rains, I ___ stay.","opts":["will","would","am","have"],"a":0,"b":0.2},
{"id":"b1-3","level":2,"type":"Grammar","cat":"Modals","q":"You ___ finish homework first.","opts":["must","can","might","could"],"a":0,"b":0.0},
{"id":"b1-4","level":2,"type":"Grammar","cat":"Prepositions","q":"She has worked here ___ 2019.","opts":["for","since","during","from"],"a":1,"b":-0.19},
{"id":"b1-5","level":2,"type":"Grammar","cat":"Relatives","q":"The book ___ is on the table is mine.","opts":["which","who","whose","whom"],"a":0,"b":0.0},
{"id":"b1-6","level":2,"type":"Grammar","cat":"Gerunds","q":"I am used ___ early.","opts":["wake","to wake","to waking","waking"],"a":2,"b":0.0},
{"id":"b1-7","level":2,"type":"Grammar","cat":"Past Perfect","q":"When we arrived they ___ dinner.","opts":["finished","had finished","have finished","finish"],"a":1,"b":0.1},
{"id":"b1-8","level":2,"type":"Grammar","cat":"Reported Speech","q":"She asked where I ___.","opts":["live","lived","am living","will live"],"a":1,"b":0.2},
{"id":"b1-9","level":2,"type":"Grammar","cat":"Correlatives","q":"Neither the manager ___ the employees knew.","opts":["or","nor","and","but"],"a":1,"b":0.1},
{"id":"b1-10","level":2,"type":"Grammar","cat":"Wishes","q":"I wish I ___ speak French.","opts":["can","could","will","may"],"a":1,"b":0.2},
{"id":"b1-11","level":2,"type":"Vocabulary","cat":"Work","q":"A colleague is someone you ___ with.","opts":["live","work","study","travel"],"a":1,"b":0.0},
{"id":"b1-12","level":2,"type":"Vocabulary","cat":"Work","q":"A promotion means ___.","opts":["lose job","higher position","fewer hours","less pay"],"a":1,"b":0.01},
{"id":"b1-13","level":2,"type":"Vocabulary","cat":"Phrasals","q":"Give up means ___.","opts":["donate","stop trying","distribute","surrender"],"a":1,"b":0.1},
{"id":"b1-14","level":2,"type":"Vocabulary","cat":"Work","q":"Company needs to ___ employees.","opts":["fire","hire","ignore","reduce"],"a":1,"b":0.02},
{"id":"b1-15","level":2,"type":"Vocabulary","cat":"Learning","q":"I need to ___ my English.","opts":["improve","decrease","forget","ignore"],"a":0,"b":0.0},
{"id":"b1-16","level":2,"type":"Vocabulary","cat":"Feelings","q":"She is ___ about the trip.","opts":["excited","exciting","excitement","excite"],"a":0,"b":0.0},
{"id":"b1-17","level":2,"type":"Vocabulary","cat":"Business","q":"Meeting was ___ until next week.","opts":["cancelled","postponed","finished","started"],"a":1,"b":0.0},
{"id":"b1-18","level":2,"type":"Vocabulary","cat":"Finance","q":"He has ___ in the stock market.","opts":["experience","knowledge","investment","practice"],"a":2,"b":0.0},
{"id":"b1-19","level":2,"type":"Reading","cat":"Comprehension","q":"John saved months, booked flight, felt nervous. Why nervous?","opts":["Lost money","Traveling alone","Never flew","Not stated"],"a":3,"b":0.02},
{"id":"b2-1","level":3,"type":"Grammar","cat":"Passive","q":"The report ___ yesterday.","opts":["wrote","was written","has written","is writing"],"a":1,"b":1.3},
{"id":"b2-2","level":3,"type":"Grammar","cat":"Conditionals","q":"Had I known, I ___ differently.","opts":["would act","would have acted","will act","acted"],"a":1,"b":1.21},
{"id":"b2-3","level":3,"type":"Grammar","cat":"Inversion","q":"Not until she arrived ___ the news.","opts":["she heard","did she hear","she did hear","she hears"],"a":1,"b":1.5},
{"id":"b2-4","level":3,"type":"Grammar","cat":"Adjectives","q":"Most ___ problem we've faced.","opts":["challenging","challenged","challenge","challenges"],"a":0,"b":1.0},
{"id":"b2-5","level":3,"type":"Grammar","cat":"Subjunctive","q":"Essential that every student ___ the rules.","opts":["follows","follow","following","followed"],"a":1,"b":1.4},
{"id":"b2-6","level":3,"type":"Grammar","cat":"Vocabulary","q":"Many factors ___ to the company's success.","opts":["contribute","attribute","distribute","tribute"],"a":0,"b":1.0},
{"id":"b2-7","level":3,"type":"Grammar","cat":"Passive","q":"The phenomenon ___ by researchers.","opts":["has studied","has been studied","studied","was studying"],"a":1,"b":1.31},
{"id":"b2-8","level":3,"type":"Grammar","cat":"Conditionals","q":"Without her help, we ___ failed.","opts":["will have","would have","had","have"],"a":1,"b":1.22},
{"id":"b2-9","level":3,"type":"Grammar","cat":"Subjunctive","q":"He insisted the meeting ___ postponed.","opts":["is","be","was","has been"],"a":1,"b":1.41},
{"id":"b2-10","level":3,"type":"Vocabulary","cat":"Academic","q":"Results were ___ \u2014 unexplained.","opts":["inconclusive","conclusive","decided","determined"],"a":0,"b":1.1},
{"id":"b2-11","level":3,"type":"Vocabulary","cat":"Business","q":"Company's ___ increased this quarter.","opts":["revenue","venue","adventure","inventory"],"a":0,"b":1.01},
{"id":"b2-12","level":3,"type":"Vocabulary","cat":"Collocations","q":"Documentary ___ light on the issue.","opts":["shed","threw","gave","made"],"a":0,"b":1.1},
{"id":"b2-13","level":3,"type":"Vocabulary","cat":"Business","q":"Agreement was ___ by both parties.","opts":["signed","ignored","delayed","rejected"],"a":0,"b":1.02},
{"id":"b2-14","level":3,"type":"Vocabulary","cat":"Academic","q":"We must ___ the problem now.","opts":["address","ignore","postpone","forget"],"a":0,"b":1.11},
{"id":"b2-15","level":3,"type":"Vocabulary","cat":"Phrasals","q":"Research ___ new possibilities.","opts":["opened up","closed off","ran out","gave away"],"a":0,"b":1.11},
{"id":"b2-16","level":3,"type":"Reading","cat":"Comprehension","q":"Team persevered despite setbacks. Meaning?","opts":["Gave up","Continued despite","Started late","Changed plans"],"a":1,"b":1.03},
{"id":"c1-1","level":4,"type":"Grammar","cat":"Inversion","q":"___ had she finished when the phone rang.","opts":["No sooner","Not only","Hardly","Never"],"a":2,"b":2.51},
{"id":"c1-2","level":4,"type":"Grammar","cat":"Subjunctive","q":"Imperative that he ___ the report today.","opts":["submits","submit","submitted","submitting"],"a":1,"b":2.42},
{"id":"c1-3","level":4,"type":"Grammar","cat":"Compounds","q":"The longer you wait, ___ it becomes.","opts":["the harder","harder","more hard","the more hard"],"a":0,"b":2.0},
{"id":"c1-4","level":4,"type":"Grammar","cat":"Conditionals","q":"Without funding the project ___.","opts":["would fail","would have failed","failed","will fail"],"a":1,"b":2.23},
{"id":"c1-5","level":4,"type":"Grammar","cat":"Relatives","q":"Author ___ books are bestsellers.","opts":["which","who","whose","whom"],"a":2,"b":2.01},
{"id":"c1-6","level":4,"type":"Grammar","cat":"Inversion","q":"Seldom ___ such dedication.","opts":["I have seen","have I seen","I saw","I see"],"a":1,"b":2.52},
{"id":"c1-7","level":4,"type":"Grammar","cat":"Correlatives","q":"Not only did she finish, ___ she broke the record.","opts":["but also","and also","also","but"],"a":0,"b":2.11},
{"id":"c1-8","level":4,"type":"Vocabulary","cat":"Nuance","q":"Ubiquitous means ___.","opts":["rare","found everywhere","expensive","unique"],"a":1,"b":2.2},
{"id":"c1-9","level":4,"type":"Vocabulary","cat":"Academic","q":"Compelling and ___ argument.","opts":["persuasive","persuaded","persuading","persuasion"],"a":0,"b":2.12},
{"id":"c1-10","level":4,"type":"Vocabulary","cat":"Skill","q":"She navigated the situation with ___.","opts":["finesse","force","fear","fancy"],"a":0,"b":2.1},
{"id":"c1-11","level":4,"type":"Vocabulary","cat":"Academic","q":"Study ___ a correlation.","opts":["established","created","built","founded"],"a":0,"b":2.13},
{"id":"c1-12","level":4,"type":"Vocabulary","cat":"Academic","q":"Policy has far-reaching ___.","opts":["implications","implied","implies","implication"],"a":0,"b":2.14},
{"id":"c1-13","level":4,"type":"Vocabulary","cat":"Nuance","q":"His remarks were ___ and inappropriate.","opts":["tactless","tactful","tactic","tactile"],"a":0,"b":2.21},
{"id":"c1-14","level":4,"type":"Reading","cat":"Comprehension","q":"Ubiquitous coffee shops means they are ___.","opts":["very few","everywhere","expensive","closed"],"a":1,"b":2.04},
{"id":"c2-1","level":5,"type":"Grammar","cat":"Conditionals","q":"Without her, it ___ catastrophic.","opts":["would become","would have become","became","will become"],"a":1,"b":3.24},
{"id":"c2-2","level":5,"type":"Grammar","cat":"Inversion","q":"Never ___ such a phenomenon.","opts":["we witnessed","have we witnessed","we have witnessed","we witness"],"a":1,"b":3.53},
{"id":"c2-3","level":5,"type":"Vocabulary","cat":"Idioms","q":"Pull out all the stops means ___.","opts":["remove obstacles","make every effort","stop completely","cancel plans"],"a":1,"b":3.3},
{"id":"c2-4","level":5,"type":"Vocabulary","cat":"Precision","q":"Ephemeral means ___.","opts":["lasting long","lasting short","very large","very small"],"a":1,"b":3.2},
{"id":"c2-5","level":5,"type":"Vocabulary","cat":"Precision","q":"Verbose means ___.","opts":["concise","wordy","simple","poetic"],"a":1,"b":3.21},
{"id":"c2-6","level":5,"type":"Vocabulary","cat":"Precision","q":"Cogent means ___.","opts":["convincing","confusing","contradictory","convoluted"],"a":0,"b":3.22},
{"id":"c2-7","level":5,"type":"Vocabulary","cat":"Precision","q":"Nonplussed means ___.","opts":["impressed","confused","relaxed","determined"],"a":1,"b":3.23},
{"id":"c2-8","level":5,"type":"Vocabulary","cat":"Precision","q":"Her argument was ___.","opts":["lucid","vague","unclear","confusing"],"a":0,"b":3.24},
{"id":"a1-36","level":0,"type":"Grammar","cat":"A1","q":"I ___ a doctor.","opts":["am","is","are","be"],"a":0,"b":-2.3},
{"id":"a1-37","level":0,"type":"Grammar","cat":"A1","q":"We ___ students.","opts":["am","is","are","be"],"a":2,"b":-2.29},
{"id":"a1-38","level":0,"type":"Grammar","cat":"A1","q":"She ___ not here.","opts":["am","is","are","be"],"a":1,"b":-2.28},
{"id":"a1-39","level":0,"type":"Grammar","cat":"A1","q":"___ you from Iran?","opts":["Is","Are","Am","Do"],"a":1,"b":-2.27},
{"id":"a1-40","level":0,"type":"Grammar","cat":"A1","q":"This is ___ pen.","opts":["I","my","me","mine"],"a":1,"b":-2.26},
{"id":"a1-41","level":0,"type":"Grammar","cat":"Vocabulary","q":"They are ___ the house.","opts":["at","in","on","to"],"a":1,"b":-1.99},
{"id":"a1-42","level":0,"type":"Grammar","cat":"Vocabulary","q":"I ___ like apples.","opts":["don't","doesn't","not","am"],"a":0,"b":-1.98},
{"id":"a1-43","level":0,"type":"Grammar","cat":"Vocabulary","q":"She ___ like milk.","opts":["don't","doesn't","not","isn't"],"a":1,"b":-1.97},
{"id":"a1-44","level":0,"type":"Grammar","cat":"Vocabulary","q":"How old are you? I ___ ten.","opts":["am","is","are","have"],"a":0,"b":-1.96},
{"id":"a1-45","level":0,"type":"Grammar","cat":"Vocabulary","q":"What is this? ___ is a book.","opts":["This","That","It","He"],"a":2,"b":-1.95},
{"id":"a2-18","level":1,"type":"Grammar","cat":"A2","q":"I ___ breakfast at 7 am.","opts":["have","has","had","having"],"a":0,"b":-1.1},
{"id":"a2-19","level":1,"type":"Grammar","cat":"A2","q":"She ___ to work by train.","opts":["go","goes","going","went"],"a":1,"b":-1.09},
{"id":"a2-20","level":1,"type":"Grammar","cat":"A2","q":"We ___ not see the movie yet.","opts":["have","has","did","are"],"a":0,"b":-1.08},
{"id":"a2-21","level":1,"type":"Grammar","cat":"A2","q":"This bag is ___ than that one.","opts":["big","bigger","biggest","more big"],"a":1,"b":-1.07},
{"id":"a2-22","level":1,"type":"Grammar","cat":"A2","q":"He is interested ___ history.","opts":["in","on","at","for"],"a":0,"b":-1.06},
{"id":"a2-23","level":1,"type":"Grammar","cat":"Vocabulary","q":"They ___ playing soccer now.","opts":["am","is","are","be"],"a":2,"b":-0.94},
{"id":"a2-24","level":1,"type":"Grammar","cat":"Vocabulary","q":"I have ___ finished my homework.","opts":["yet","already","still","ever"],"a":1,"b":-0.93},
{"id":"a2-25","level":1,"type":"Grammar","cat":"Vocabulary","q":"She is the ___ girl in class.","opts":["tall","taller","tallest","most tall"],"a":2,"b":-0.92},
{"id":"a2-26","level":1,"type":"Grammar","cat":"Vocabulary","q":"Can you help ___?","opts":["I","my","me","mine"],"a":2,"b":-0.91},
{"id":"a2-27","level":1,"type":"Grammar","cat":"Vocabulary","q":"There are ___ apples on the table.","opts":["some","any","a","an"],"a":0,"b":-0.9},
{"id":"b1-20","level":2,"type":"Grammar","cat":"B1","q":"He ___ been to London twice.","opts":["has","have","is","was"],"a":0,"b":0.0},
{"id":"b1-21","level":2,"type":"Grammar","cat":"B1","q":"They ___ working when I called.","opts":["were","was","are","have"],"a":0,"b":0.01},
{"id":"b1-22","level":2,"type":"Grammar","cat":"B1","q":"I would go if I ___ enough money.","opts":["had","have","will have","would have"],"a":0,"b":0.02},
{"id":"b1-23","level":2,"type":"Grammar","cat":"B1","q":"She told me that she ___ coming.","opts":["is","was","will be","would be"],"a":1,"b":0.03},
{"id":"b1-24","level":2,"type":"Grammar","cat":"B1","q":"This is the man ___ helped me.","opts":["which","who","whose","whom"],"a":1,"b":0.04},
{"id":"b1-25","level":2,"type":"Grammar","cat":"Vocabulary","q":"We look forward ___ hearing from you.","opts":["to","for","in","at"],"a":0,"b":0.11},
{"id":"b1-26","level":2,"type":"Grammar","cat":"Vocabulary","q":"He is not used ___ up early.","opts":["get","to get","to getting","getting"],"a":2,"b":0.12},
{"id":"b1-27","level":2,"type":"Grammar","cat":"Vocabulary","q":"The exam ___ of three parts.","opts":["consists","contains","includes","composes"],"a":0,"b":0.13},
{"id":"b1-28","level":2,"type":"Grammar","cat":"Vocabulary","q":"She couldn't help ___ at the joke.","opts":["laugh","laughing","laughed","to laugh"],"a":1,"b":0.14},
{"id":"b1-29","level":2,"type":"Grammar","cat":"Vocabulary","q":"I have been waiting ___ two hours.","opts":["for","since","during","from"],"a":0,"b":0.15},
{"id":"b2-17","level":3,"type":"Grammar","cat":"B2","q":"The building ___ in 1990.","opts":["built","was built","has built","is built"],"a":1,"b":1.1},
{"id":"b2-18","level":3,"type":"Grammar","cat":"B2","q":"No sooner had he left ___ it started raining.","opts":["than","then","when","after"],"a":0,"b":1.11},
{"id":"b2-19","level":3,"type":"Grammar","cat":"B2","q":"Under no circumstances ___ enter this room.","opts":["you should","should you","you may","you can"],"a":1,"b":1.12},
{"id":"b2-20","level":3,"type":"Grammar","cat":"B2","q":"She is accustomed ___ in a big city.","opts":["live","living","to live","to living"],"a":3,"b":1.13},
{"id":"b2-21","level":3,"type":"Grammar","cat":"B2","q":"The data ___ collected over six months.","opts":["was","were","is","are"],"a":1,"b":1.14},
{"id":"b2-22","level":3,"type":"Grammar","cat":"Vocabulary","q":"Had he studied harder, he ___ passed.","opts":["will have","would have","would","had"],"a":1,"b":1.16},
{"id":"b2-23","level":3,"type":"Grammar","cat":"Vocabulary","q":"The article ___ by a famous journalist.","opts":["wrote","was written","has written","writes"],"a":1,"b":1.17},
{"id":"b2-24","level":3,"type":"Grammar","cat":"Vocabulary","q":"He has a wide ___ of experience.","opts":["range","ranger","ranging","ranged"],"a":0,"b":1.18},
{"id":"b2-25","level":3,"type":"Grammar","cat":"Vocabulary","q":"The results are ___ with our hypothesis.","opts":["consistent","consisting","consistently","consist"],"a":0,"b":1.19},
{"id":"b2-26","level":3,"type":"Grammar","cat":"Vocabulary","q":"She has a ___ for learning languages.","opts":["gift","present","talent","skill"],"a":2,"b":1.2},
{"id":"c1-15","level":4,"type":"Grammar","cat":"C1","q":"Never ___ I seen such beauty.","opts":["have","had","did","was"],"a":0,"b":2.0},
{"id":"c1-16","level":4,"type":"Grammar","cat":"C1","q":"Only after the meeting ___ he realize his mistake.","opts":["did","does","was","has"],"a":0,"b":2.01},
{"id":"c1-17","level":4,"type":"Grammar","cat":"C1","q":"The report ___ further investigation.","opts":["warrants","warrents","warrant","warranted"],"a":0,"b":2.02},
{"id":"c1-18","level":4,"type":"Grammar","cat":"C1","q":"Her argument was both cogent and ___.","opts":["persuasive","persuaded","persuasion","persuade"],"a":0,"b":2.03},
{"id":"c1-19","level":4,"type":"Grammar","cat":"C1","q":"The implications of the study are ___.","opts":["far-reaching","far-reached","far-reach","far-reaches"],"a":0,"b":2.04},
{"id":"c1-20","level":4,"type":"Grammar","cat":"Vocabulary","q":"She has an ___ ability to solve problems.","opts":["uncanny","canny","cunning","unknown"],"a":0,"b":2.21},
{"id":"c1-21","level":4,"type":"Grammar","cat":"Vocabulary","q":"The meeting was ___ to discuss the issue.","opts":["convened","convented","conceived","convinced"],"a":0,"b":2.22},
{"id":"c1-22","level":4,"type":"Grammar","cat":"Vocabulary","q":"His approach was fundamentally ___.","opts":["flawed","flaw","flawless","flawing"],"a":0,"b":2.23},
{"id":"c1-23","level":4,"type":"Grammar","cat":"Vocabulary","q":"The author's latest work is a ___ achievement.","opts":["remarkable","remark","remarked","remarking"],"a":0,"b":2.24},
{"id":"c1-24","level":4,"type":"Grammar","cat":"Vocabulary","q":"It is ___ that more research is needed.","opts":["evident","evidence","evidently","evidential"],"a":0,"b":2.25},
{"id":"c2-9","level":5,"type":"Grammar","cat":"C2","q":"Her speech was both eloquent and ___.","opts":["moving","move","moved","movement"],"a":0,"b":3.0},
{"id":"c2-10","level":5,"type":"Grammar","cat":"C2","q":"The novel is a ___ exploration of identity.","opts":["profound","profoundly","profundity","profounds"],"a":0,"b":3.01},
{"id":"c2-11","level":5,"type":"Grammar","cat":"C2","q":"His actions were ___ \u2014 they could not be justified.","opts":["inexcusable","excusable","excusing","excused"],"a":0,"b":3.02},
{"id":"c2-12","level":5,"type":"Grammar","cat":"C2","q":"The painting is a ___ of color and light.","opts":["masterpiece","master","mastering","masterly"],"a":0,"b":3.03},
{"id":"c2-13","level":5,"type":"Grammar","cat":"C2","q":"She has an ___ knowledge of the subject.","opts":["intimate","intimated","intimating","intimation"],"a":0,"b":3.04},
{"id":"c2-14","level":5,"type":"Grammar","cat":"Vocabulary","q":"The situation is more ___ than it appears.","opts":["complex","complexity","complexion","complexed"],"a":0,"b":3.26},
{"id":"c2-15","level":5,"type":"Grammar","cat":"Vocabulary","q":"His ___ of the evidence was convincing.","opts":["interpretation","interpreting","interpreted","interpretive"],"a":0,"b":3.27},
{"id":"c2-16","level":5,"type":"Grammar","cat":"Vocabulary","q":"The results are ___ with previous findings.","opts":["consistent","consisting","consistently","consist"],"a":0,"b":3.28},
{"id":"c2-17","level":5,"type":"Grammar","cat":"Vocabulary","q":"She is a ___ figure in the literary world.","opts":["prominent","prominently","prominence","prominent's"],"a":0,"b":3.29},
{"id":"c2-18","level":5,"type":"Grammar","cat":"Vocabulary","q":"The work is a ___ of historical research.","opts":["culmination","culminate","culminating","culminated"],"a":0,"b":3.3},
  // ══════ Block 2: v2 duplicates (60 questions) ══════
{"id":"a1-2-v2","level":0,"type":"Grammar","cat":"A1","q":"The cat is ___ the table.","opts":["on","in","at","under"],"a":0,"b":-2.25},
{"id":"a1-3-v2","level":0,"type":"Grammar","cat":"A1","q":"I ___ my teeth every day.","opts":["brush","brushes","brushing","brushed"],"a":0,"b":-2.24},
{"id":"a1-4-v2","level":0,"type":"Grammar","cat":"A1","q":"She ___ to school every day.","opts":["go","goes","going","went"],"a":1,"b":-2.23},
{"id":"a1-5-v2","level":0,"type":"Grammar","cat":"A1","q":"We ___ happy today.","opts":["am","is","are","be"],"a":2,"b":-2.22},
{"id":"a1-6-v2","level":0,"type":"Grammar","cat":"A1","q":"___ you like pizza?","opts":["Does","Do","Is","Are"],"a":1,"b":-2.21},
{"id":"a1-7-v2","level":0,"type":"Grammar","cat":"A1","q":"My favorite color ___ blue.","opts":["am","is","are","be"],"a":1,"b":-2.2},
{"id":"a1-8-v2","level":0,"type":"Grammar","cat":"A1","q":"They are ___ the park.","opts":["in","on","at","to"],"a":0,"b":-2.19},
{"id":"a1-9-v2","level":0,"type":"Grammar","cat":"A1","q":"I ___ a red car.","opts":["have","has","had","having"],"a":0,"b":-2.18},
{"id":"a1-10-v2","level":0,"type":"Grammar","cat":"A1","q":"She ___ not like cold weather.","opts":["do","does","is","are"],"a":1,"b":-2.17},
{"id":"a1-11-v2","level":0,"type":"Grammar","cat":"A1","q":"The baby is ___.","opts":["sleep","sleeps","sleeping","slept"],"a":2,"b":-2.16},
{"id":"a2-2-v2","level":1,"type":"Grammar","cat":"A2","q":"I ___ a shower every morning.","opts":["make","take","do","have"],"a":1,"b":-1.05},
{"id":"a2-3-v2","level":1,"type":"Grammar","cat":"A2","q":"She ___ to the gym yesterday.","opts":["go","goes","went","going"],"a":2,"b":-1.04},
{"id":"a2-4-v2","level":1,"type":"Grammar","cat":"A2","q":"We are going ___ holiday next week.","opts":["in","on","at","for"],"a":1,"b":-1.03},
{"id":"a2-5-v2","level":1,"type":"Grammar","cat":"A2","q":"This is ___ than that one.","opts":["good","better","best","well"],"a":1,"b":-1.02},
{"id":"a2-6-v2","level":1,"type":"Grammar","cat":"A2","q":"I have ___ finished the book.","opts":["already","yet","still","ever"],"a":0,"b":-1.01},
{"id":"a2-7-v2","level":1,"type":"Grammar","cat":"A2","q":"He is interested ___ learning French.","opts":["to","in","at","for"],"a":1,"b":-1.0},
{"id":"a2-8-v2","level":1,"type":"Grammar","cat":"A2","q":"They ___ never been to London.","opts":["have","has","had","are"],"a":0,"b":-0.99},
{"id":"a2-9-v2","level":1,"type":"Grammar","cat":"A2","q":"The restaurant is ___ the corner.","opts":["on","in","at","by"],"a":0,"b":-0.98},
{"id":"a2-10-v2","level":1,"type":"Grammar","cat":"A2","q":"I need to buy ___ milk.","opts":["a","an","some","any"],"a":2,"b":-0.97},
{"id":"a2-11-v2","level":1,"type":"Grammar","cat":"A2","q":"She can speak English very ___.","opts":["good","well","better","best"],"a":1,"b":-0.96},
{"id":"b1-2-v2","level":2,"type":"Grammar","cat":"B1","q":"He is responsible ___ training new staff.","opts":["for","to","in","at"],"a":0,"b":0.05},
{"id":"b1-3-v2","level":2,"type":"Grammar","cat":"B1","q":"I'm looking forward ___ you next week.","opts":["see","to see","seeing","to seeing"],"a":3,"b":0.06},
{"id":"b1-4-v2","level":2,"type":"Grammar","cat":"B1","q":"The company ___ in 1995.","opts":["founded","was founded","founds","founding"],"a":1,"b":0.07},
{"id":"b1-5-v2","level":2,"type":"Grammar","cat":"B1","q":"She insisted ___ coming with us.","opts":["on","in","at","for"],"a":0,"b":0.08},
{"id":"b1-6-v2","level":2,"type":"Grammar","cat":"B1","q":"We managed ___ finish on time.","opts":["to","in","for","at"],"a":0,"b":0.09},
{"id":"b1-7-v2","level":2,"type":"Grammar","cat":"B1","q":"I don't mind ___ late.","opts":["work","working","to work","worked"],"a":1,"b":0.1},
{"id":"b1-8-v2","level":2,"type":"Grammar","cat":"B1","q":"This is the school ___ I studied.","opts":["which","that","where","who"],"a":2,"b":0.11},
{"id":"b1-9-v2","level":2,"type":"Grammar","cat":"B1","q":"If I ___ you, I would accept.","opts":["am","was","were","are"],"a":2,"b":0.12},
{"id":"b1-10-v2","level":2,"type":"Grammar","cat":"B1","q":"She suggested ___ a taxi.","opts":["take","taking","to take","took"],"a":1,"b":0.13},
{"id":"b1-11-v2","level":2,"type":"Grammar","cat":"B1","q":"The more you practice, ___ you get.","opts":["better","the better","best","the best"],"a":1,"b":0.14},
{"id":"b2-2-v2","level":3,"type":"Grammar","cat":"B2","q":"The project ___ by next month.","opts":["will complete","will be completed","completes","completed"],"a":1,"b":1.15},
{"id":"b2-3-v2","level":3,"type":"Grammar","cat":"B2","q":"Rarely ___ such dedication.","opts":["I have seen","have I seen","I saw","I see"],"a":1,"b":1.16},
{"id":"b2-4-v2","level":3,"type":"Grammar","cat":"B2","q":"I wish I ___ more time.","opts":["have","had","had had","would have"],"a":1,"b":1.17},
{"id":"b2-5-v2","level":3,"type":"Grammar","cat":"B2","q":"The committee ___ made its decision.","opts":["has","have","are","is"],"a":0,"b":1.18},
{"id":"b2-6-v2","level":3,"type":"Grammar","cat":"B2","q":"Should you have questions, please ___ me.","opts":["ask","to ask","asked","asking"],"a":0,"b":1.19},
{"id":"b2-7-v2","level":3,"type":"Grammar","cat":"B2","q":"Neither the manager nor the employees ___ satisfied.","opts":["was","were","has","have"],"a":1,"b":1.2},
{"id":"b2-8-v2","level":3,"type":"Grammar","cat":"B2","q":"She has a talent ___ negotiation.","opts":["for","in","of","at"],"a":0,"b":1.21},
{"id":"b2-9-v2","level":3,"type":"Grammar","cat":"B2","q":"Despite the challenges, we ___ to succeed.","opts":["managed","succeeded","could","might"],"a":0,"b":1.22},
{"id":"b2-10-v2","level":3,"type":"Grammar","cat":"B2","q":"The new regulation ___ all employees.","opts":["affects","effects","infects","defects"],"a":0,"b":1.23},
{"id":"b2-11-v2","level":3,"type":"Grammar","cat":"B2","q":"It is vital that everyone ___ present.","opts":["is","be","was","will be"],"a":1,"b":1.24},
{"id":"c1-2-v2","level":4,"type":"Grammar","cat":"C1","q":"Hardly ___ the room when the alarm rang.","opts":["had he entered","he had entered","did he enter","he entered"],"a":0,"b":2.05},
{"id":"c1-3-v2","level":4,"type":"Grammar","cat":"C1","q":"It is essential that the report ___ ready.","opts":["is","be","was","will be"],"a":1,"b":2.06},
{"id":"c1-4-v2","level":4,"type":"Vocabulary","cat":"C1","q":"The consequences of the action were ___.","opts":["far-reaching","far-reached","far-reach","far-reaches"],"a":0,"b":2.07},
{"id":"c1-5-v2","level":4,"type":"Vocabulary","cat":"C1","q":"Her analysis was both thorough and ___.","opts":["insightful","insight","insighting","insightfully"],"a":0,"b":2.08},
{"id":"c1-6-v2","level":4,"type":"Vocabulary","cat":"C1","q":"The crisis ___ immediate action.","opts":["requires","require","required","requiring"],"a":0,"b":2.09},
{"id":"c1-7-v2","level":4,"type":"Vocabulary","cat":"C1","q":"Her argument rests on a ___ assumption.","opts":["fundamental","fundamentally","fundamentalist","fundament"],"a":0,"b":2.1},
{"id":"c1-8-v2","level":4,"type":"Vocabulary","cat":"C1","q":"The film ___ elements of drama and comedy.","opts":["combines","combine","combined","combining"],"a":0,"b":2.11},
{"id":"c1-9-v2","level":4,"type":"Vocabulary","cat":"C1","q":"The audit ___ several accounting errors.","opts":["revealed","reveal","revealing","reveals"],"a":0,"b":2.12},
{"id":"c1-10-v2","level":4,"type":"Vocabulary","cat":"C1","q":"His ___ of the poem was unique.","opts":["interpretation","interpret","interpreting","interpreted"],"a":0,"b":2.13},
{"id":"c1-11-v2","level":4,"type":"Vocabulary","cat":"C1","q":"The peace talks have reached a crucial ___.","opts":["point","points","pointing","pointed"],"a":0,"b":2.14},
{"id":"c2-2-v2","level":5,"type":"Vocabulary","cat":"C2","q":"Her lecture was both engaging and ___.","opts":["thought-provoking","thought-provoke","thought-provoked","thought-provokes"],"a":0,"b":3.05},
{"id":"c2-3-v2","level":5,"type":"Vocabulary","cat":"C2","q":"His expertise in the field is ___.","opts":["unparalleled","paralleling","paralleled","unparalleling"],"a":0,"b":3.06},
{"id":"c2-4-v2","level":5,"type":"Vocabulary","cat":"C2","q":"The discovery was the ___ of years of research.","opts":["culmination","culminate","culminating","culminated"],"a":0,"b":3.07},
{"id":"c2-5-v2","level":5,"type":"Vocabulary","cat":"C2","q":"Her argument was so ___ that it changed minds.","opts":["persuasive","persuade","persuaded","persuasion"],"a":0,"b":3.08},
{"id":"c2-6-v2","level":5,"type":"Vocabulary","cat":"C2","q":"The task was ___ — nobody wanted to do it.","opts":["unenviable","enviable","envied","envying"],"a":0,"b":3.09},
{"id":"c2-7-v2","level":5,"type":"Vocabulary","cat":"C2","q":"She is a ___ expert in her field.","opts":["leading","lead","led","leader"],"a":0,"b":3.1},
{"id":"c2-8-v2","level":5,"type":"Vocabulary","cat":"C2","q":"Her writing is both sophisticated and ___.","opts":["accessible","access","accessed","accessing"],"a":0,"b":3.11},
{"id":"c2-9-v2","level":5,"type":"Vocabulary","cat":"C2","q":"The theory was ___ by experimental data.","opts":["supported","support","supporting","supports"],"a":0,"b":3.12},
{"id":"c2-10-v2","level":5,"type":"Vocabulary","cat":"C2","q":"His intentions were ___ — nobody could figure them out.","opts":["mysterious","mysteriously","mystery","mysteries"],"a":0,"b":3.13},
{"id":"c2-11-v2","level":5,"type":"Vocabulary","cat":"C2","q":"The movie is a ___ reminder of our past.","opts":["powerful","powerfully","power","powered"],"a":0,"b":3.14},
  // ══════ Block 3: v3 duplicates (60 questions) ══════
{"id":"a1-2-v3","level":0,"type":"Grammar","cat":"A1","q":"I like ___ cats.","opts":["a","the","-","an"],"a":2,"b":-2.15},
{"id":"a1-3-v3","level":0,"type":"Grammar","cat":"A1","q":"He ___ his homework every day.","opts":["does","do","doing","did"],"a":0,"b":-2.14},
{"id":"a1-4-v3","level":0,"type":"Grammar","cat":"A1","q":"They ___ to the park yesterday.","opts":["go","goes","went","going"],"a":2,"b":-2.13},
{"id":"a1-5-v3","level":0,"type":"Grammar","cat":"A1","q":"He ___ at home now.","opts":["am","is","are","be"],"a":1,"b":-2.12},
{"id":"a1-6-v3","level":0,"type":"Grammar","cat":"A1","q":"___ she speak English?","opts":["Does","Do","Is","Are"],"a":0,"b":-2.11},
{"id":"a1-7-v3","level":0,"type":"Grammar","cat":"A1","q":"My shoes ___ black.","opts":["am","is","are","be"],"a":2,"b":-2.1},
{"id":"a1-8-v3","level":0,"type":"Grammar","cat":"A1","q":"The book is ___ the shelf.","opts":["in","on","at","to"],"a":1,"b":-2.09},
{"id":"a1-9-v3","level":0,"type":"Grammar","cat":"A1","q":"She ___ long hair.","opts":["have","has","had","having"],"a":1,"b":-2.08},
{"id":"a1-10-v3","level":0,"type":"Grammar","cat":"A1","q":"We ___ like spicy food.","opts":["do","does","is","are"],"a":0,"b":-2.07},
{"id":"a1-11-v3","level":0,"type":"Grammar","cat":"A1","q":"They are ___ TV now.","opts":["watch","watches","watching","watched"],"a":2,"b":-2.06},
{"id":"a2-2-v3","level":1,"type":"Grammar","cat":"A2","q":"I ___ lunch at noon.","opts":["have","has","had","having"],"a":0,"b":-0.95},
{"id":"a2-3-v3","level":1,"type":"Grammar","cat":"A2","q":"She ___ a movie last night.","opts":["watch","watches","watched","watching"],"a":2,"b":-0.94},
{"id":"a2-4-v3","level":1,"type":"Grammar","cat":"A2","q":"I'm interested ___ art.","opts":["in","on","at","for"],"a":0,"b":-0.93},
{"id":"a2-5-v3","level":1,"type":"Grammar","cat":"A2","q":"This is the ___ restaurant in town.","opts":["good","better","best","well"],"a":2,"b":-0.92},
{"id":"a2-6-v3","level":1,"type":"Grammar","cat":"A2","q":"Has he called ___?","opts":["already","yet","still","ever"],"a":1,"b":-0.91},
{"id":"a2-7-v3","level":1,"type":"Grammar","cat":"A2","q":"She is good ___ math.","opts":["to","in","at","for"],"a":2,"b":-0.9},
{"id":"a2-8-v3","level":1,"type":"Grammar","cat":"A2","q":"I have ___ seen that film.","opts":["already","yet","still","ever"],"a":0,"b":-0.89},
{"id":"a2-9-v3","level":1,"type":"Grammar","cat":"A2","q":"The cat is hiding ___ the bed.","opts":["in","on","under","at"],"a":2,"b":-0.88},
{"id":"a2-10-v3","level":1,"type":"Grammar","cat":"A2","q":"Would you like ___ water?","opts":["a","an","some","any"],"a":2,"b":-0.87},
{"id":"a2-11-v3","level":1,"type":"Grammar","cat":"A2","q":"She plays the piano very ___.","opts":["good","well","better","best"],"a":1,"b":-0.86},
{"id":"b1-2-v3","level":2,"type":"Grammar","cat":"B1","q":"He is capable ___ doing the job.","opts":["for","of","in","at"],"a":1,"b":0.15},
{"id":"b1-3-v3","level":2,"type":"Grammar","cat":"B1","q":"I am fond ___ classical music.","opts":["for","of","in","with"],"a":1,"b":0.16},
{"id":"b1-4-v3","level":2,"type":"Grammar","cat":"B1","q":"The exhibition ___ last month.","opts":["held","was held","has held","holding"],"a":1,"b":0.17},
{"id":"b1-5-v3","level":2,"type":"Grammar","cat":"B1","q":"She insisted ___ paying for dinner.","opts":["in","on","for","at"],"a":1,"b":0.18},
{"id":"b1-6-v3","level":2,"type":"Grammar","cat":"B1","q":"We managed ___ the problem on time.","opts":["solve","solving","to solve","solved"],"a":2,"b":0.19},
{"id":"b1-7-v3","level":2,"type":"Grammar","cat":"B1","q":"She doesn't enjoy ___ alone.","opts":["travel","to travel","traveling","traveled"],"a":2,"b":0.2},
{"id":"b1-8-v3","level":2,"type":"Grammar","cat":"B1","q":"This is the restaurant ___ we first met.","opts":["which","that","where","who"],"a":2,"b":0.21},
{"id":"b1-9-v3","level":2,"type":"Grammar","cat":"B1","q":"If I had more time, I ___ travel more.","opts":["will","would","can","may"],"a":1,"b":0.22},
{"id":"b1-10-v3","level":2,"type":"Grammar","cat":"B1","q":"He recommended ___ the early train.","opts":["take","taking","to take","took"],"a":1,"b":0.23},
{"id":"b1-11-v3","level":2,"type":"Grammar","cat":"B1","q":"The earlier you start, ___ you'll finish.","opts":["sooner","the sooner","soonest","the soonest"],"a":1,"b":0.24},
{"id":"b2-2-v3","level":3,"type":"Grammar","cat":"B2","q":"The new policy ___ next quarter.","opts":["will implement","will be implemented","implements","implementing"],"a":1,"b":1.25},
{"id":"b2-3-v3","level":3,"type":"Grammar","cat":"B2","q":"Not once ___ her complain about the workload.","opts":["I heard","did I hear","I did hear","heard I"],"a":1,"b":1.26},
{"id":"b2-4-v3","level":3,"type":"Grammar","cat":"B2","q":"I wish I ___ the opportunity earlier.","opts":["had","had had","have","would have"],"a":1,"b":1.27},
{"id":"b2-5-v3","level":3,"type":"Grammar","cat":"B2","q":"The research team ___ significant progress.","opts":["has made","is made","making","make"],"a":0,"b":1.28},
{"id":"b2-6-v3","level":3,"type":"Grammar","cat":"B2","q":"Should the plan fail, we ___ another approach.","opts":["will try","would try","would have tried","try"],"a":0,"b":1.29},
{"id":"b2-7-v3","level":3,"type":"Grammar","cat":"B2","q":"The findings ___ published in a journal.","opts":["was","were","has","have"],"a":1,"b":1.3},
{"id":"b2-8-v3","level":3,"type":"Grammar","cat":"B2","q":"She has a knack ___ solving complex problems.","opts":["for","in","of","at"],"a":0,"b":1.31},
{"id":"b2-9-v3","level":3,"type":"Grammar","cat":"B2","q":"In spite of the rain, we ___ to enjoy the trip.","opts":["managed","succeeded","could","might"],"a":0,"b":1.32},
{"id":"b2-10-v3","level":3,"type":"Grammar","cat":"B2","q":"The agreement ___ all parties involved.","opts":["affects","effects","infects","defects"],"a":0,"b":1.33},
{"id":"b2-11-v3","level":3,"type":"Grammar","cat":"B2","q":"It is essential that everyone ___ the rules.","opts":["follows","follow","followed","following"],"a":1,"b":1.34},
{"id":"c1-2-v3","level":4,"type":"Grammar","cat":"C1","q":"Barely ___ the presentation when the questions began.","opts":["had he finished","he had finished","did he finish","he finished"],"a":0,"b":2.15},
{"id":"c1-3-v3","level":4,"type":"Grammar","cat":"C1","q":"It is crucial that the data ___ verified.","opts":["be","is","was","will be"],"a":0,"b":2.16},
{"id":"c1-4-v3","level":4,"type":"Vocabulary","cat":"C1","q":"The ramifications of the decision were ___.","opts":["far-reaching","far-reached","far-reach","far-reaches"],"a":0,"b":2.17},
{"id":"c1-5-v3","level":4,"type":"Vocabulary","cat":"C1","q":"Her thesis was both original and ___.","opts":["provocative","provoked","provoking","provocation"],"a":0,"b":2.18},
{"id":"c1-6-v3","level":4,"type":"Vocabulary","cat":"C1","q":"The situation ___ immediate intervention.","opts":["demands","demand","demanded","demanding"],"a":0,"b":2.19},
{"id":"c1-7-v3","level":4,"type":"Vocabulary","cat":"C1","q":"Her reasoning is based on a ___ principle.","opts":["core","cores","corer","core's"],"a":0,"b":2.2},
{"id":"c1-8-v3","level":4,"type":"Vocabulary","cat":"C1","q":"The artist's work ___ conventional genres.","opts":["blends","blend","blended","blending"],"a":0,"b":2.21},
{"id":"c1-9-v3","level":4,"type":"Vocabulary","cat":"C1","q":"The investigation ___ widespread corruption.","opts":["uncovered","uncover","uncovering","uncovers"],"a":0,"b":2.22},
{"id":"c1-10-v3","level":4,"type":"Vocabulary","cat":"C1","q":"His ___ of the text was highly original.","opts":["reading","read","reader","readable"],"a":0,"b":2.23},
{"id":"c1-11-v3","level":4,"type":"Vocabulary","cat":"C1","q":"The negotiations have reached a critical ___.","opts":["stage","stages","staging","staged"],"a":0,"b":2.24},
{"id":"c2-2-v3","level":5,"type":"Vocabulary","cat":"C2","q":"The lecture was both informative and ___.","opts":["stimulating","stimulate","stimulated","stimulation"],"a":0,"b":3.15},
{"id":"c2-3-v3","level":5,"type":"Vocabulary","cat":"C2","q":"His command of the subject is ___.","opts":["extraordinary","extraordinarily","extraordinariness","extraordinary's"],"a":0,"b":3.16},
{"id":"c2-4-v3","level":5,"type":"Vocabulary","cat":"C2","q":"The symphony is the ___ of his life's work.","opts":["apotheosis","apotheoses","apotheotic","apotheosize"],"a":0,"b":3.17},
{"id":"c2-5-v3","level":5,"type":"Vocabulary","cat":"C2","q":"Her reasoning was so ___ that it convinced everyone.","opts":["compelling","compel","compelled","compulsion"],"a":0,"b":3.18},
{"id":"c2-6-v3","level":5,"type":"Vocabulary","cat":"C2","q":"The position was ___ — no one wanted it.","opts":["unenviable","enviable","envied","envying"],"a":0,"b":3.19},
{"id":"c2-7-v3","level":5,"type":"Vocabulary","cat":"C2","q":"She is a ___ authority on Renaissance art.","opts":["leading","lead","led","leader"],"a":0,"b":3.2},
{"id":"c2-8-v3","level":5,"type":"Vocabulary","cat":"C2","q":"Her prose is both elegant and ___.","opts":["accessible","access","accessed","accessing"],"a":0,"b":3.21},
{"id":"c2-9-v3","level":5,"type":"Vocabulary","cat":"C2","q":"The hypothesis was ___ by subsequent experiments.","opts":["validated","validate","validating","validation"],"a":0,"b":3.22},
{"id":"c2-10-v3","level":5,"type":"Vocabulary","cat":"C2","q":"His motives were ___ — no one could guess them.","opts":["inscrutable","inscrutably","inscrutability","inscrutable's"],"a":0,"b":3.23},
{"id":"c2-11-v3","level":5,"type":"Vocabulary","cat":"C2","q":"The story is a ___ reminder of our shared humanity.","opts":["powerful","powerfully","power","powered"],"a":0,"b":3.24},
  // ══════ Block 4: v4 duplicates (60 questions) ══════
{"id":"a1-2-v4","level":0,"type":"Grammar","cat":"A1","q":"The dog is ___ the garden.","opts":["on","in","at","under"],"a":1,"b":-2.05},
{"id":"a1-3-v4","level":0,"type":"Grammar","cat":"A1","q":"They ___ breakfast at 8.","opts":["have","has","having","had"],"a":0,"b":-2.04},
{"id":"a1-4-v4","level":0,"type":"Grammar","cat":"A1","q":"He ___ to work by car.","opts":["go","goes","going","went"],"a":1,"b":-2.03},
{"id":"a1-5-v4","level":0,"type":"Grammar","cat":"A1","q":"The children ___ outside.","opts":["am","is","are","be"],"a":2,"b":-2.02},
{"id":"a1-6-v4","level":0,"type":"Grammar","cat":"A1","q":"___ he play football?","opts":["Does","Do","Is","Are"],"a":0,"b":-2.01},
{"id":"a1-7-v4","level":0,"type":"Grammar","cat":"A1","q":"The flowers ___ beautiful.","opts":["am","is","are","be"],"a":2,"b":-2.0},
{"id":"a1-8-v4","level":0,"type":"Grammar","cat":"A1","q":"The pen is ___ the desk.","opts":["in","on","at","by"],"a":1,"b":-1.99},
{"id":"a1-9-v4","level":0,"type":"Grammar","cat":"A1","q":"We ___ a big house.","opts":["have","has","had","having"],"a":0,"b":-1.98},
{"id":"a1-10-v4","level":0,"type":"Grammar","cat":"A1","q":"I ___ like getting up early.","opts":["do","does","am","are"],"a":0,"b":-1.97},
{"id":"a1-11-v4","level":0,"type":"Grammar","cat":"A1","q":"She is ___ a letter.","opts":["write","writes","writing","wrote"],"a":2,"b":-1.96},
{"id":"a2-2-v4","level":1,"type":"Grammar","cat":"A2","q":"We ___ dinner at 8 pm.","opts":["have","has","had","having"],"a":0,"b":-0.85},
{"id":"a2-3-v4","level":1,"type":"Grammar","cat":"A2","q":"I ___ a great time yesterday.","opts":["have","has","had","having"],"a":2,"b":-0.84},
{"id":"a2-4-v4","level":1,"type":"Grammar","cat":"A2","q":"She is afraid ___ spiders.","opts":["in","on","of","at"],"a":2,"b":-0.83},
{"id":"a2-5-v4","level":1,"type":"Grammar","cat":"A2","q":"This is the ___ day of my life.","opts":["good","better","best","well"],"a":2,"b":-0.82},
{"id":"a2-6-v4","level":1,"type":"Grammar","cat":"A2","q":"I haven't finished ___.","opts":["already","yet","still","ever"],"a":1,"b":-0.81},
{"id":"a2-7-v4","level":1,"type":"Grammar","cat":"A2","q":"He is afraid ___ heights.","opts":["to","in","of","for"],"a":2,"b":-0.8},
{"id":"a2-8-v4","level":1,"type":"Grammar","cat":"A2","q":"She has never ___ to Paris.","opts":["be","been","was","being"],"a":1,"b":-0.79},
{"id":"a2-9-v4","level":1,"type":"Grammar","cat":"A2","q":"The cat is hiding ___ the bed.","opts":["in","on","under","at"],"a":2,"b":-0.78},
{"id":"a2-10-v4","level":1,"type":"Grammar","cat":"A2","q":"Would you like ___ water?","opts":["a","an","some","any"],"a":2,"b":-0.77},
{"id":"a2-11-v4","level":1,"type":"Grammar","cat":"A2","q":"She plays the piano very ___.","opts":["good","well","better","best"],"a":1,"b":-0.76},
{"id":"b1-2-v4","level":2,"type":"Grammar","cat":"B1","q":"He is capable ___ doing the job.","opts":["for","of","in","at"],"a":1,"b":0.25},
{"id":"b1-3-v4","level":2,"type":"Grammar","cat":"B1","q":"I am fond ___ classical music.","opts":["for","of","in","with"],"a":1,"b":0.26},
{"id":"b1-4-v4","level":2,"type":"Grammar","cat":"B1","q":"The exhibition ___ last month.","opts":["held","was held","has held","holding"],"a":1,"b":0.27},
{"id":"b1-5-v4","level":2,"type":"Grammar","cat":"B1","q":"She insisted ___ paying for dinner.","opts":["in","on","for","at"],"a":1,"b":0.28},
{"id":"b1-6-v4","level":2,"type":"Grammar","cat":"B1","q":"We managed ___ the problem on time.","opts":["solve","solving","to solve","solved"],"a":2,"b":0.29},
{"id":"b1-7-v4","level":2,"type":"Grammar","cat":"B1","q":"She doesn't enjoy ___ alone.","opts":["travel","to travel","traveling","traveled"],"a":2,"b":0.3},
{"id":"b1-8-v4","level":2,"type":"Grammar","cat":"B1","q":"This is the restaurant ___ we first met.","opts":["which","that","where","who"],"a":2,"b":0.31},
{"id":"b1-9-v4","level":2,"type":"Grammar","cat":"B1","q":"If I had more time, I ___ travel more.","opts":["will","would","can","may"],"a":1,"b":0.32},
{"id":"b1-10-v4","level":2,"type":"Grammar","cat":"B1","q":"He recommended ___ the early train.","opts":["take","taking","to take","took"],"a":1,"b":0.33},
{"id":"b1-11-v4","level":2,"type":"Grammar","cat":"B1","q":"The earlier you start, ___ you'll finish.","opts":["sooner","the sooner","soonest","the soonest"],"a":1,"b":0.34},
{"id":"b2-2-v4","level":3,"type":"Grammar","cat":"B2","q":"The new policy ___ next quarter.","opts":["will implement","will be implemented","implements","implementing"],"a":1,"b":1.35},
{"id":"b2-3-v4","level":3,"type":"Grammar","cat":"B2","q":"Not once ___ her complain about the workload.","opts":["I heard","did I hear","I did hear","heard I"],"a":1,"b":1.36},
{"id":"b2-4-v4","level":3,"type":"Grammar","cat":"B2","q":"I wish I ___ the opportunity earlier.","opts":["had","had had","have","would have"],"a":1,"b":1.37},
{"id":"b2-5-v4","level":3,"type":"Grammar","cat":"B2","q":"The research team ___ significant progress.","opts":["has made","is made","making","make"],"a":0,"b":1.38},
{"id":"b2-6-v4","level":3,"type":"Grammar","cat":"B2","q":"Should the plan fail, we ___ another approach.","opts":["will try","would try","would have tried","try"],"a":1,"b":1.39},
{"id":"b2-7-v4","level":3,"type":"Grammar","cat":"B2","q":"The findings ___ published in a journal.","opts":["was","were","has","have"],"a":1,"b":1.4},
{"id":"b2-8-v4","level":3,"type":"Grammar","cat":"B2","q":"She has a knack ___ solving complex problems.","opts":["for","in","of","at"],"a":0,"b":1.41},
{"id":"b2-9-v4","level":3,"type":"Grammar","cat":"B2","q":"In spite of the rain, we ___ to enjoy the trip.","opts":["managed","succeeded","could","might"],"a":0,"b":1.42},
{"id":"b2-10-v4","level":3,"type":"Grammar","cat":"B2","q":"The agreement ___ all parties involved.","opts":["affects","effects","infects","defects"],"a":0,"b":1.43},
{"id":"b2-11-v4","level":3,"type":"Grammar","cat":"B2","q":"It is essential that everyone ___ the rules.","opts":["follows","follow","followed","following"],"a":1,"b":1.44},
{"id":"c1-2-v4","level":4,"type":"Grammar","cat":"C1","q":"Barely ___ the presentation when the questions began.","opts":["had he finished","he had finished","did he finish","he finished"],"a":0,"b":2.25},
{"id":"c1-3-v4","level":4,"type":"Grammar","cat":"C1","q":"It is crucial that the data ___ verified.","opts":["be","is","was","will be"],"a":0,"b":2.26},
{"id":"c1-4-v4","level":4,"type":"Vocabulary","cat":"C1","q":"The ramifications of the decision were ___.","opts":["far-reaching","far-reached","far-reach","far-reaches"],"a":0,"b":2.27},
{"id":"c1-5-v4","level":4,"type":"Vocabulary","cat":"C1","q":"Her thesis was both original and ___.","opts":["provocative","provoked","provoking","provocation"],"a":0,"b":2.28},
{"id":"c1-6-v4","level":4,"type":"Vocabulary","cat":"C1","q":"The situation ___ immediate intervention.","opts":["demands","demand","demanded","demanding"],"a":0,"b":2.29},
{"id":"c1-7-v4","level":4,"type":"Vocabulary","cat":"C1","q":"Her reasoning is based on a ___ principle.","opts":["core","cores","corer","core's"],"a":0,"b":2.3},
{"id":"c1-8-v4","level":4,"type":"Vocabulary","cat":"C1","q":"The artist's work ___ conventional genres.","opts":["blends","blend","blended","blending"],"a":0,"b":2.31},
{"id":"c1-9-v4","level":4,"type":"Vocabulary","cat":"C1","q":"The investigation ___ widespread corruption.","opts":["uncovered","uncover","uncovering","uncovers"],"a":0,"b":2.32},
{"id":"c1-10-v4","level":4,"type":"Vocabulary","cat":"C1","q":"His ___ of the text was highly original.","opts":["reading","read","reader","readable"],"a":0,"b":2.33},
{"id":"c1-11-v4","level":4,"type":"Vocabulary","cat":"C1","q":"The negotiations have reached a critical ___.","opts":["stage","stages","staging","staged"],"a":0,"b":2.34},
{"id":"c2-2-v4","level":5,"type":"Vocabulary","cat":"C2","q":"The lecture was both informative and ___.","opts":["stimulating","stimulate","stimulated","stimulation"],"a":0,"b":3.25},
{"id":"c2-3-v4","level":5,"type":"Vocabulary","cat":"C2","q":"His command of the subject is ___.","opts":["extraordinary","extraordinarily","extraordinariness","extraordinary's"],"a":0,"b":3.26},
{"id":"c2-4-v4","level":5,"type":"Vocabulary","cat":"C2","q":"The symphony is the ___ of his life's work.","opts":["apotheosis","apotheoses","apotheotic","apotheosize"],"a":0,"b":3.27},
{"id":"c2-5-v4","level":5,"type":"Vocabulary","cat":"C2","q":"Her reasoning was so ___ that it convinced everyone.","opts":["compelling","compel","compelled","compulsion"],"a":0,"b":3.28},
{"id":"c2-6-v4","level":5,"type":"Vocabulary","cat":"C2","q":"The position was ___ — no one wanted it.","opts":["unenviable","enviable","envied","envying"],"a":0,"b":3.29},
{"id":"c2-7-v4","level":5,"type":"Vocabulary","cat":"C2","q":"She is a ___ authority on Renaissance art.","opts":["leading","lead","led","leader"],"a":0,"b":3.3},
{"id":"c2-8-v4","level":5,"type":"Vocabulary","cat":"C2","q":"Her prose is both elegant and ___.","opts":["accessible","access","accessed","accessing"],"a":0,"b":3.31},
{"id":"c2-9-v4","level":5,"type":"Vocabulary","cat":"C2","q":"The hypothesis was ___ by subsequent experiments.","opts":["validated","validate","validating","validation"],"a":0,"b":3.32},
{"id":"c2-10-v4","level":5,"type":"Vocabulary","cat":"C2","q":"His motives were ___ — no one could guess them.","opts":["inscrutable","inscrutably","inscrutability","inscrutable's"],"a":0,"b":3.33},
{"id":"c2-11-v4","level":5,"type":"Vocabulary","cat":"C2","q":"The story is a ___ reminder of our shared humanity.","opts":["powerful","powerfully","power","powered"],"a":0,"b":3.34}
];